### ISSUE TITLE
[Mod Support] Diet

### ISSUE THREAD

**Issue by ghost** [ISenseHostility/ImprovedBerries#1]
Not an issue, just a suggestion: Support for [Diet](https://github.com/TheIllusiveC4/Diet) would be great.

**Comment by ISenseHostility** [comment]
Just opened a Pull Request, so if the Diet maintainers merge it, both Sweet Berry Wine and Sweet Berry Pie will be added to the 'sugars' and 'fruits' categories. I'll close the topic when it is merged.

**Comment by ghost** [comment]
Sweet (berries), thank you!

**Comment by ISenseHostility** [comment]
The PR was merged, so Diet now has support.

**Comment by ghost** [comment]
Thanks again!
